config/routes.rb
Rails.application.routes.draw do
  resources :setlist do
    resources :songs
  end

  root 'setlist#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setlist.rb
class Setlist < ApplicationRecord
  has_many :songs

  def total_duration
    all_durations = []
    self.songs.each do |x|
      duration = x.minutes * 60 + x.seconds
      all_durations << duration
    end
      return all_durations.inject(0){|sum,x| sum + x }
  end

  def set_minutes
    self.total_duration / 60
  end

  def set_seconds
    if self.total_duration % 60 > 9
      return self.total_duration % 60
    else
      return "0#{self.total_duration % 60}"
    end
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :setlist

  validates :title, length: { minimum: 1, message: "ERROR MESSAGE" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/setlist_controller.rb
class SetlistController < ApplicationController
  attr_accessor

  def index
    @setlists = Setlist.all
  end

  def show
    @setlist = Setlist.find(params[:id])
  end

  def update
    @setlist = Setlist.find(params[:id])

    if @setlist.update_attributes(setlist_params)
      redirect_to setlist_url(@setlist)
    else
      render :edit
    end
  end

  def create
    @setlist = Setlist.new(setlist_params)

    if setlist.save
      redirect_to show_url, notice: "You have created a setlist!"
    end
  end

  def new
    @setlist = Setlist.new
    @setlist.save
  end

  def destroy
    @setlist = Setlist.find(params[:id]).delete
      if @setlist.delete
    redirect_to new_setlist_url
  end
end

  private

  def setlist_params
    params.require(:setlist).permit(:title, :description)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_setlist

  def index
    @songs = Song.all
  end

  def create
    @song = @setlist.songs.create(song_params)

    if @song.save
      redirect_to @setlist
    else
      redirect_to @setlist, alert: "Could not add song."
    end
  end

  def update
    @setlist = Setlist.song.find(params[:id])

    if @song.update_attributes(song_params)
      redirect_to setlist_url(@setlist)
    else
      render :edit
    end
  end

  def new
    @song = Song.new
  end

  def destroy
    @song = Song.find(params[:id])
    if @song.destroy
      redirect_to @setlist
    else
      flash[:error] = "There was an error completing the item."
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  private

  def set_setlist
    @setlist = Setlist.find(params[:setlist_id])
  end

  def song_params
    params[:song].permit(:title, :minutes, :seconds)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/setlist_helper.rb
module SetlistHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Getlist</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Mada|Ubuntu" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/setlist/_form.html.erb
<%= form_for @setlist do |f| %>
  <div>
    <%= f.label :title, "Setlist Title:", :class => "setlist-label" %><br><br>
    <%= f.text_field :title, :class => "inputField", :placeholder => "...", :maxlength => 20 %>
  </div>
  <br>
  <%= f.submit "Create", :class => "create"%>
<% end %>

app/views/setlist/_song.html.erb
<%= form_for [@setlist, Song.new] do |f| %>
  <div>
    <%= f.text_field :title, :maxlength => 28, :class => "InputField", :placeholder => "Song title" %>
  </div>
  <div>
    <%= f.number_field :minutes, :min => 0, :max => 1000, :placeholder => "min", :class => "MinInputField", :value => 0 %>
  </div>
  <div>
    <%= f.number_field :seconds, :min => 0, :max => 59, :placeholder => "sec", :class => "SecInputField", :value => 0 %>
  </div>
  <%= f.submit "+", :class => "submitButton" %>
<% end %>

app/views/setlist/index.html.erb
<!-- This is the current root page to create setlist -->
<h1>Welcome to Getlist</h1>
<html>
<head>
<body>
<br><br>
<%= link_to "Create Setlist", new_setlist_path %>
</body>
</head>
</html>

app/views/setlist/new.html.erb
<!-- Create your setlist title here -->
<html>
  <body>
    <div class="header-cont">
      <div class="header">
        <h1>Welcome to Getlist</h1>
      </div>

      <div class="content">
        <%= render 'form' %>
      </div>
      <div class="footer-new"><p class="total-duration">By David N. Wood<p>
      </div>
    </div>
  </body>
</html>
<!-- <footer>By David N. Wood 2017</footer> -->

app/views/setlist/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>

    <!-- Data submission -->
  <body>
    <div class="header-cont">
      <div class="header-2">
        <h2><%= @setlist.title %></h2></div>
      <div class="content">
        <%= render 'song' %>
          <table class="song-table">

          <% @setlist.songs.each do |x| %>


            <tr id="<%= x.id %>">
              <td class="song-title"><%= x.title %></td>
              <% if x.seconds < 10 %>
              <td class="song-duration"><%= "#{x.minutes}:0#{x.seconds}" %></td>
              <% else %>
              <td class="song-duration"><%= "#{x.minutes}:#{x.seconds}" %></td>
              <% end %>

              <td>
                <button type="button" i class="fa fa-times" aria-hidden="true" id="<%= x.id %>"></button>
              </td>
            </tr>
          <% end %>

          </table>

      <!-- Setlist Duration -->
      <div class="total-duration">total setlist duration:</div>
    <div class="total-timer"><% if @setlist.set_minutes == 0 && @setlist.set_seconds == 0 %>
      <%= "00:00" %>
      <% else %>
      <%= @setlist.set_minutes %>:<%= @setlist.set_seconds %>
      <% end %></div>
      <div class ="del-setlist"><%= link_to 'delete', setlist_path(@setlist), method: :delete, data: { confirm: 'Are you sure?' }, :id => "delete-sl" %></div>
    </div>
  </body>
</html>